# Module Configuration File
#
# This file configures Hugo module settings, particularly module mounts which
# define how content is organized within the project.
#
# Mounts specify file paths in your project that Hugo should use when building
# the site. They allow for custom directory structures and integrating content
# from different locations.

## content
[[mounts]]
  disableWatch = false
  source = "content"
  target = "content"
  [mounts.sites]
    [mounts.sites.complements]
    [mounts.sites.matrix]

## data
[[mounts]]
  source = "node_modules/@thulite/doks-core/data"
  target = "data"

[[mounts]]
  disableWatch = false
  source = "data"
  target = "data"
  [mounts.sites]
    [mounts.sites.complements]
    [mounts.sites.matrix]

## layouts
[[mounts]]
  disableWatch = false
  source = "layouts"
  target = "layouts"
  [mounts.sites]
    [mounts.sites.complements]
    [mounts.sites.matrix]

[[mounts]]
  # File filter: '!' prefix excludes files from the mount. Excluding 'home.html' prevents the theme's
  # default homepage from loading, allowing the custom homepage in local 'layouts/home.html' to take precedence.
  files = ['! home.html']
  source = "node_modules/@thulite/doks-core/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@thulite/core/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@thulite/seo/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@thulite/images/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@thulite/inline-svg/layouts"
  target = "layouts"

## i18n
[[mounts]]
  source = "node_modules/@thulite/doks-core/i18n"
  target = "i18n"

[[mounts]]
  disableWatch = false
  source = "i18n"
  target = "i18n"
  [mounts.sites]
    [mounts.sites.complements]
    [mounts.sites.matrix]

## archetypes
[[mounts]]
  source = "node_modules/@thulite/doks-core/archetypes"
  target = "archetypes"

[[mounts]]
  disableWatch = false
  source = "archetypes"
  target = "archetypes"
  [mounts.sites]
    [mounts.sites.complements]
    [mounts.sites.matrix]

## assets
[[mounts]]
  source = "node_modules/@thulite/core/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@thulite/doks-core/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@tabler/icons/icons"
  target = "assets/svgs/tabler-icons"

[[mounts]]
  source = "node_modules/@thulite/images/assets"
  target = "assets"

[[mounts]]
  disableWatch = false
  source = "assets"
  target = "assets"
  [mounts.sites]
    [mounts.sites.complements]
    [mounts.sites.matrix]

## static
[[mounts]]
  source = "node_modules/@thulite/doks-core/static"
  target = "static"

[[mounts]]
  disableWatch = false
  source = "static"
  target = "static"
  [mounts.sites]
    [mounts.sites.complements]
    [mounts.sites.matrix]
