# Meta Data for SEO

## Homepage
title = "Shivratan Singh Rajvi"
titleSeparator = "-"
titleAddition = "Shivratan Singh Rajvi's Blog"
description = "DevOps Engineer, a seasoned blogger with 4+ years of experience in the Information Technology."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "shivratanrajvi.in"
titleHome = "Shivratan Singh Rajvi"

## Twitter Cards
twitterSite = "@shivratanrajvi"
twitterCreator = "@shivratanrajvi"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Shivratan Rajvi"
schemaAuthor = "Shivratan Singh Rajvi"
schemaAuthorTwitter = "https://twitter.com/shivratanrajvi"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/shivratanrajvi/"
schemaAuthorGitHub = "https://github.com/shivratanrajvi"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/shivratanrajvi"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/shivratanrajvi"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Managed by <a class=\"text-muted\" href=\"https://linkedin.com/in/shivratanrajvi">Shivratan Singh Rajvi</a>"

# Feed
copyRight = "Copyright (c) 2023-2024 Shivratan Singh Rajvi"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
