# Meta Data for SEO

## Homepage
title = "Doks"
titleSeparator = "-"
titleAddition = "Modern Documentation Theme"
description = "Hyas is a Hugo starter helping you build modern websites that are secure, fast, and SEO-ready â€” by default."

## Open Graph
images = ["hyas.png"]
ogLocale = "en_US"
titleHome = "Hyas Hugo Starter"

## Twitter Cards
twitterSite = "@gethyas"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Hyas"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-US"
schemaLogo = "logo-hyas.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "hyas.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/gethyas"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/hyas"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

## Documentation
# docsVersion = "1.0"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

# Images

## defaultImage
defaultImage = "default-image.jpg" # put in `./assets/images/`

## imaging
[imaging]
  anchor = 'Smart'
  bgColor = '#fff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'Lanczos'

## lazyimg
[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  # maxSize = "1920x"
  maxSize = "1366x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = ""
  noscript = true

  errorHandler = "warning"

[sections]
  sectionNav = ["docs", "guides", "books"]

[options]
  lazySizes = true # no longer an option (included by default)
  clipBoard = true # no longer an option (included by default)
  instantPage = false # no longer an option (replaced with quicklink, included by default)
  flexSearch = true # new setup
  searchSectionsShow = [] # new setup
  searchSectionsIndex = [] # new setup
  darkMode = true # new setup
  bootStrapJs = true # new setup
  breadCrumb = false # new setup
  highLight = false # no longer an option (dropped, use Hugo's Chroma syntax highlighting)
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false # new setup
  navbarSticky = true # same option
  toTopButton = false # new setup (included by default)
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
